Pinned setuptools to avoid regression
 CommandExecutionError: /usr/local/lib/python2.7/dist-packages/pkg_resources.py:2443: PEP440Warning: 'python-debian (0.1.21-nmu2ubuntu2)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.